### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rfakit** [javadr/Maktabkhooneh-dl#1]
با سلام من خطای زیر رو دریافت میکنم. لطف میکنین راهنمایی بفرمایین

```
Traceback (most recent call last):
  File "/opt/Maktabkhooneh-dl/maktabkhooneh-dl.py", line 6, in <module>
    maktabkhooneh_dl.main()
  File "/opt/Maktabkhooneh-dl/maktabkhooneh/maktabkhooneh_dl.py", line 27, in main
    _ = course.extract()
  File "/opt/Maktabkhooneh-dl/maktabkhooneh/course.py", line 49, in extract
    self._getChapterLinks()  # makes the download urls of the inlcluded lesson(s)
  File "/opt/Maktabkhooneh-dl/maktabkhooneh/course.py", line 127, in _getChapterLinks
    chapter = self.driver.find_elements(By.LINK_TEXT,
IndexError: list index out of range
```

**Comment by javadr** [comment]
Provide me with more details.
It seems some things dropped!

**Comment by javadr** [comment]
You might call it incorrectly as I don't find any issues and everything works like a charm.
